version: '2'
services:
  zabbix-proxy:
    restart: unless-stopped
    image: ${CONTAINER_IMAGE}:${CONTAINER_VERSION}
    container_name: zabbix-proxy
    ports:
      - "10051:10051"
    volumes:
      - ./zabbix/enc:/var/lib/zabbix/enc:z
      - ./zabbix/externalscripts:/usr/lib/zabbix/externalscripts:z
      - ./zabbix/mibs:/var/lib/zabbix/mibs:z
      - ./zabbix/modules:/var/lib/zabbix/modules:z
      - ./zabbix/snmptraps:/var/lib/zabbix/snmptraps:z
    links:
      - zabbix-snmptraps
    env_file:
      - proxy.env

  zabbix-snmptraps:
    restart: unless-stopped
    image: zabbix/zabbix-snmptraps:alpine-7.0-latest
    container_name: zabbix-snmptraps
    ports:
      - "162:1162/udp"
    volumes:
      - ./zabbix/snmptraps:/var/lib/zabbix/snmptraps:z
      - ./zabbix/mibs:/var/lib/zabbix/mibs:z
